apiVersion: v1
kind: MasterConfig
oauthConfig:
  identityProviders:
  - name: htpasswd_auth
    challenge: true
    login: true
    mappingMethod: claim
    provider:
      apiVersion: v1
      kind: HTPasswdPasswordIdentityProvider
      file: /etc/origin/master/htpasswd
kubernetesMasterConfig:
  apiServerArguments:
    runtime-config:
    - api/all=true
  controllerArguments:
    enable-hostpath-provisioner:
    - "true"
etcdClientInfo:
  urls:
  - https://127.0.0.1:2379
  ca: /etc/origin/master/etcd-ca.crt
  certFile: /etc/origin/master/etcd-client.crt
  keyFile: /etc/origin/master/etcd-client.key
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: /etc/origin/master/master.server.crt
  keyFile: /etc/origin/master/master.server.key
  ca: /etc/origin/master/ca.crt
  clientCA: /etc/origin/master/client-ca.crt
admissionConfig:
  pluginConfig:
    "BuildDefaults":
      configuration:
        apiVersion: v1
        kind: BuildDefaultsConfig
        gitHTTPProxy: http://proxy.example.com:8080
        gitHTTPSProxy: https://proxy.example.com:8443
controllerConfig:
  controllers:
  - "*"
  - -serviceaccount
  - -serviceaccount-tokens
